name: Geral

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Executa diariamente às 2h da manhã
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch:

jobs:
  build_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    - run: |
        # do something
        git push

  create_database_backup:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MySQL
      uses: mysql-actions/setup-mysql@v1
      with:
        mysql version: '8.0'

    - name: Backup MySQL database
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      run: |
        mysqldump -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > backup.sql

    - name: Upload backup to repository
      uses: actions/upload-artifact@v2
      with:
        name: mysql-backup
        path: backup.sql

  generate_hourly_log:
    if: github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate log file
      run: |
        TIMESTAMP=$(date +"%Y%m%d%H%M%S")
        echo "Log generated at $TIMESTAMP" > hourly_log_$TIMESTAMP.txt

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: hourly-log
        path: hourly_log_*.txt
